In [2]:
import numpy as np
size = 8
chessboard = np.ones((size,size), dtype=np.int16)

queenCoordinate = (4,7) #(Y,X) for visual correctioness

print(chessboard)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [3]:
def changeInLinesToZero(chessboard, queenCoordinate):
    chessboard[:, queenCoordinate[1]] = 0
    chessboard[queenCoordinate[0]:queenCoordinate[0]+1, :] = 0

In [4]:
changeInLinesToZero(chessboard, queenCoordinate)

In [5]:
print(chessboard)

[[1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0]]


In [6]:
def changeDiagonalsToZero(chessboard, queenCoordinate):
    
    #upperleftQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y >= 0 and x >= 0):
        chessboard[y,x] = 0
        y = y - 1
        x = x - 1
    #UpperRightQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y >= 0 and x < size):
        chessboard[y,x] = 0
        y = y - 1
        x = x + 1
    #LowerLeftQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y < size and x >= 0):
        chessboard[y,x] = 0
        y = y + 1
        x = x - 1
    #LowerRightQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y < size and x < size):
        chessboard[y,x] = 0
        y = y + 1
        x = x + 1
    
        

In [7]:
changeDiagonalsToZero(chessboard, queenCoordinate)

In [8]:
print(chessboard)

[[1 1 1 0 1 1 1 0]
 [1 1 1 1 0 1 1 0]
 [1 1 1 1 1 0 1 0]
 [1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 0]
 [1 1 1 1 1 0 1 0]
 [1 1 1 1 0 1 1 0]]


In [11]:
###Start at 0,0
# add queen and flip zeros
#add queen to next open spot and flip to zeros
#repeat previous step until there is no spots left
#Revert previous step and add queen to spot after next spot
import random as rand
def findNewQueenCoordinate(chessboard):
    yValue = rand.randint(0, size-1)
    xValue = rand.randint(0, size-1)
    if chessboard[yValue][xValue] == 1:
        return (yValue, xValue)
    return (-1, -1)

In [14]:
queenCombinations = []
queenSet = []

numberOfQueensLeft = 8
for i in range(0, 1000000):
    size = 8
    chessboard = np.ones((size,size), dtype=np.int16)
    
    queenSet = []

    numberOfQueensLeft = 8
    while (numberOfQueensLeft > 0):

        newQueenCoordinate = findNewQueenCoordinate(chessboard)
        if (newQueenCoordinate != (-1,-1)):
            numberOfQueensLeft = numberOfQueensLeft - 1
            changeInLinesToZero(chessboard, newQueenCoordinate)
            changeDiagonalsToZero(chessboard, newQueenCoordinate)
#             print(newQueenCoordinate)
#             print(chessboard)
            queenSet.append(newQueenCoordinate)
        else:
#             print("OUT OF OPTIONS")
            break
    if (numberOfQueensLeft == 0):
        queenCombinations.append(queenSet)
print(queenCombinations)

[]


In [ ]:
####ABOVE IS A FAILED PATH TO SOLUTION

In [37]:
def checkAboveVerticalLines(chessboard, queenCoordinate):
    
    xVal = queenCoordinate[0] - 1
#     print(queenCoordinate)
#     print('XVAL: ', xVal)
    while(xVal >= 0):
#         print('(', xVal, queenCoordinate[1], ')')
#         print(chessboard[xVal, queenCoordinate[1]])
#         print(chessboard[xVal, queenCoordinate[1]])
        if (chessboard[xVal, queenCoordinate[1]] == 0):
            return False
        xVal = xVal - 1
    return True

In [38]:
def checkUpperDiagonals(chessboard, queenCoordinate):
    #upperleftQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y >= 0 and x >= 0):
        if (chessboard[y,x] == 0):
            return False
        y = y - 1
        x = x - 1
    #UpperRightQuadrant
    y = queenCoordinate[0]
    x = queenCoordinate[1]
    while(y >= 0 and x < size):
        if (chessboard[y,x] == 0):
            return False
        y = y - 1
        x = x + 1
    return True

In [107]:
import numpy as np
size = 8
successfulBoards = []
for firstQueen in range(0, 7):
    chessboard = np.ones((size,size), dtype=np.int16)
    
    queenCoordinate = (0,firstQueen) #(Y,X) for visual correctioness
    chessboard[queenCoordinate[0]][queenCoordinate[1]] = 0

#     print(chessboard)
    queenCoordinates = []
    queenCoordinates.append(queenCoordinate)
    queensPlaced = 0
    startLoop = (firstQueen + 1) % (size-1)
    while(queensPlaced < 7):
#         print('begin While loop', queensPlaced)
        previousQueensPlaced = queensPlaced
        for x in range(startLoop, size):
            newQueenCoordinate = (queenCoordinates[queensPlaced][0]+1, x)
            if (checkAboveVerticalLines(chessboard, newQueenCoordinate) and checkUpperDiagonals(chessboard, newQueenCoordinate)):
                queenCoordinates.append(newQueenCoordinate)
                chessboard[newQueenCoordinate[0]][newQueenCoordinate[1]] = 0
#                 print(chessboard)
                queensPlaced = queensPlaced + 1
                startLoop = 0
                break
        if (previousQueensPlaced == queensPlaced):
            # If for loop finds no successful spot for a queen
            # Reduce y coordinate by 1 and remove queen from row above
            # Start searching for a new spot one x spot to the right
            chessboard[queensPlaced][queenCoordinates[queensPlaced][1]] = 1
            startLoop = queenCoordinates[queensPlaced][1] + 1
            queenCoordinates.pop(queensPlaced)
#             print('queensPlaced', queensPlaced)
#             print(chessboard)
            queensPlaced = queensPlaced - 1
        
    successfulBoards.append(chessboard)
    
    for boards in successfulBoards:
        print(boards)
        
        
#         startLoop = queenCoordinates[queensPlaced-1][1]
#         print('startloop: ', startLoop)
#         print('(', newQueenCoordinate[0], newQueenCoordinate[1], ')')
#         chessboard[newQueenCoordinate[0]][newQueenCoordinate[1]] = 1
#         print(chessboard)
#         queenCoordinates.pop(queensPlaced-1)
#         queensPlaced = queensPlaced - 1
        

[[0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]]
[[0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]]
[[1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 0 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 1 1 1 0 1 1 1]]
[[0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1]
 [1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]]
[[1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 0 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 1 1 1 0 1 1 1]]
[[1 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 1]]
[[0 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 1 1]
 [1 1 